### ISSUE TITLE
Bug with the Wilder Wild mod

### ISSUE THREAD

**Issue by CartOon29-GIT** [mindsh4ke/security-for-fabric#1]
The ancient horn from the Wilder Wild mod can kill the Turret entity, causing a crash when trying to pick up or enable/disable the turret block. I'm pretty sure this can be solved by increasing the health of the entity to 40, though. I think the entity can also die due to suffocation, the warden's ranged attack, basically any mob if it angers them and maybe a few others I haven't found yet.

**Comment by mindsh4ke** [comment]
This bug is now fixed in 1.1.1 version, I also fixed some other bugs related to the turret entity, thanks for reporting!!! :)
